.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH TUNESBROWSER 1 "December 27, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
tunesbrowser \- an audio player for X, that can browse iTunes shares.
.SH SYNOPSIS
.B tunesbrowser [switches]
.SH DESCRIPTION
.B tunesbrowser
is a small media player for X whose main feature is its ability
to browse Apple's iTunes shares.
.PP
.SH SWITCHES
.TP
.B --debugmsg <debug options>
Turn on and off debug channels and classes.
.B <debug options>
is a comma seperated list of classes and channels to turn on or off, in the form of
(+/-)foo. Currently the only available debug classes are
.B err, trace
and
.B warn.
.SH OTHER INFO
For more information regarding
.B tunesbrowser
please visit the tunesbrowser homepage:
.B http://craz.net/programs/itunes/tunesbrowser.html
.SH AUTHOR
tunesbrowser was written by David Hammerton <craz@crazney.net>
.PP
This manual page was written by Simon Freiberg <fryboy@optusnet.com.au>,
for the Ubuntu project (but may be used by others).
